modLoader = "javafml"
loaderVersion = "[41,)"
license = "GNU AGPLv3"

[[mods]]
modId = "walljump"
version = "${version}"
displayName = "Wall-Jump! UNOFFICIAL"
credits = "Credits to genandnic for creating Wall-Jump!"
authors = "dangbroitsdon"
issueTrackerURL = "https://github.com/dangbroitsdon/Wall-Jump-Unofficial/issues"
description = '''
Jump from wall to wall! Wall jump, double jump, speed jump, fence jump, etc.
'''
logoFile = "icon.png"

[[dependencies.walljump]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.walljump]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.walljump]]
modId = "architectury"
mandatory = true
versionRange = "[5.7.28,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.walljump]]
modId = "cloth_config"
mandatory = true
versionRange = "[7.0.74,)"
ordering = "AFTER"
side = "BOTH"
