modLoader = "javafml"
loaderVersion = "[38,)"
license = "GNU AGPLv3"

[[mods]]
modId = "walljump"
version = "${version}"
displayName = "Wall-Jump! UNOFFICIAL [FORGE]"
credits = "Credits to genandnic for creating Wall-Jump!"
authors = "dangbroitsdon"
issueTrackerURL = "https://github.com/dangbroitsdon/Wall-Jump-Unofficial/issues"
description = '''
Jump from wall to wall! Wall jump, double jump, speed jump, fence jump, etc.
'''
logoFile = "icon.png"

[[dependencies.walljump]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.walljump]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.walljump]]
modId = "architectury"
mandatory = true
versionRange = "[3.9.66,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.walljump_forge]]
modId = "cloth_config"
mandatory = true
versionRange = "[6.2.62,)"
ordering = "AFTER"
side = "BOTH"