modLoader = "javafml"
loaderVersion = "[35,)"
license = "GNU AGPLv3"

[[mods]]
modId = "walljump"
version = "${version}"
displayName = "Wall-Jump! UNOFFICIAL [FORGE]"
credits = "Credits to Genandnic for creating Wall-Jump!"
authors = "dangbroitsdon"
issueTrackerURL = "https://github.com/dangbroitsdon/Wall-Jump-Unofficial/issues"
description = '''
Jump from wall to wall! Wall jump, double jump, speed jump, fence jump, etc.
'''
logoFile = "icon.png"

[[dependencies.walljump]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.walljump]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.walljump]]
modId = "architectury"
mandatory = true
versionRange = "[1.32.66,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.walljump]]
modId = "cloth-config"
mandatory = true
versionRange = "[4.14.64,)"
ordering = "AFTER"
side = "BOTH"